### ISSUE TITLE
Problème en essayant de rouler le jeu de base

### ISSUE THREAD

**Issue by CedricDufresne** [TEJ4M/codage-jeu#1]
Il est possibe de rouler une version de base du jeu (avec quelque modifications au code source). Le problème que nous faisons face c'est que nous pouvons seulement controller pacman chaque troisième joute. Les autres le jeu se joue de façon aléatoire. De plus le jeu qui roule n'est pas pacman vs. mais le pacman classic

**Comment by DarklordAlucard** [comment]
Voir la solution de Trois joutes en meme temps.
