### ISSUE TITLE
Trois joute en même temps

### ISSUE THREAD

**Issue by CedricDufresne** [TEJ4M/codage-jeu#2]
en roulant le code sur l'ordinateur de jordan et jonathan il est possible que plusieurs fenêtre de jeu s'ouvrent avec le jeu à different niveau.

**Comment by DarklordAlucard** [comment]
Dans /src/pacman, ouvrir Executor.java.

Trouver cette ligne:
//run the game in asynchronous mode.
		boolean visual=true;
		exec.runGameTimed(new NearestPillPacMan(),new AggressiveGhosts(),visual);
		exec.runGameTimed(new StarterPacMan(),new StarterGhosts(),visual);
		exec.runGameTimed(new HumanController(new KeyBoardInput()),new StarterGhosts(),visual);

Remplacer ces lignes par:
//run the game in asynchronous mode.
		boolean visual=true;
		//exec.runGameTimed(new NearestPillPacMan(),new AggressiveGhosts(),visual);
		//exec.runGameTimed(new StarterPacMan(),new StarterGhosts(),visual);
		exec.runGameTimed(new HumanController(new KeyBoardInput()),new StarterGhosts(),visual);

Les deux // vont faire les deux premier lignes en commentaires et vas seulement executer la derniere. Cela va aussi faire que le joueur peut controller Pacman
